## Introduction
### This project is to test my knowledge on machine learning classification problem, i will build a logistic regression model that predicts the churn probabilty of a customer.

### DEFINATION
### Churn rate, sometimes known as attrition rate, is the rate at which customers stop doing business with a company over a given period of time. Churn may also apply to the number of subscribers who cancel or don't renew a subscription. The higher your churn rate, the more customers stop buying from your business.
### now we understand what churn means, lets explore our data sets.
###### p/s The data sets is downloaded from kaggle, i might not do a lot of data cleaning

In [28]:
import  pandas as pd # for data exploration and preprocessing 
import numpy as np # numerical python, 
import matplotlib.pyplot as plt # for visualization
### import data science libaries

## Data undersanding

In [29]:
data=pd.read_csv("train.csv")

In [30]:
data.head(10).T

,0,1,2,3,4,5,6,7,8,9
state,OH,NJ,OH,OK,MA,MO,LA,WV,IN,RI
account_length,107,137,84,75,121,147,117,141,65,74
area_code,area_code_415,area_code_415,area_code_408,area_code_415,area_code_510,area_code_415,area_code_408,area_code_415,area_code_415,area_code_415
international_plan,no,no,yes,yes,no,yes,no,yes,no,no
voice_mail_plan,yes,no,no,no,yes,no,no,yes,no,no
number_vmail_messages,26,0,0,0,24,0,0,37,0,0
total_day_minutes,161.6,243.4,299.4,166.7,218.2,157.0,184.5,258.6,129.1,187.7
total_day_calls,123,114,71,113,88,79,97,84,137,127
total_day_charge,27.47,41.38,50.9,28.34,37.09,26.69,31.37,43.96,21.95,31.91
total_eve_minutes,195.5,121.2,61.9,148.3,348.5,103.1,351.6,222.0,228.5,163.4
total_eve_calls,103,110,88,122,108,94,80,111,83,148
total_eve_charge,16.62,10.3,5.26,12.61,29.62,8.76,29.89,18.87,19.42,13.89
total_night_minutes,254.4,162.6,196.9,186.9,212.6,211.8,215.8,326.4,208.8,196.0
total_night_calls,103,104,89,121,118,96,90,97,111,94
total_night_charge,11.45,7.32,8.86,8.41,9.57,9.53,9.71,14.69,9.4,8.82
total_intl_minutes,13.7,12.2,6.6,10.1,7.5,7.1,8.7,11.2,12.7,9.1
total_intl_calls,3,5,7,3,7,6,4,5,6,5
total_intl_charge,3.7,3.29,1.78,2.73,2.03,1.92,2.35,3.02,3.43,2.46
number_customer_service_calls,1,0,2,3,3,0,1,0,4,0
churn,no,no,no,no,no,no,no,no,yes,no

In [31]:
data.columns

Index(['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn'],
      dtype='object')

In [32]:
data.shape
# this data set contains 20 columns and 4250 rows, this mean it has 19 features, 1 target(churn) column and 4250 observations

(4250, 20)

In [33]:
data.isnull().sum()
# This data contains no missing values the data was downloaded from kaggle, well this is very rare in real life data sets,

state                            0
account_length                   0
area_code                        0
international_plan               0
voice_mail_plan                  0
number_vmail_messages            0
total_day_minutes                0
total_day_calls                  0
total_day_charge                 0
total_eve_minutes                0
total_eve_calls                  0
total_eve_charge                 0
total_night_minutes              0
total_night_calls                0
total_night_charge               0
total_intl_minutes               0
total_intl_calls                 0
total_intl_charge                0
number_customer_service_calls    0
churn                            0
dtype: int64

In [34]:
data.dtypes

state                             object
account_length                     int64
area_code                         object
international_plan                object
voice_mail_plan                   object
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                             object
dtype: object

In [35]:
data.churn.value_counts()

no     3652
yes     598
Name: churn, dtype: int64

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   state                          4250 non-null   object
 1   account_length                 4250 non-null   int64
 2   area_code                      4250 non-null   object
 3   international_plan             4250 non-null   object
 4   voice_mail_plan                4250 non-null   object
 5   number_vmail_messages          4250 non-null   int64
 6   total_day_minutes              4250 non-null   float64
 7   total_day_calls                4250 non-null   int64
 8   total_day_charge               4250 non-null   float64
 9   total_eve_minutes              4250 non-null   float64
 10  total_eve_calls                4250 non-null   int64
 11  total_eve_charge               4250 non-null   float64
 12  total_night_minutes            4250 non-null   float64
 13  total_night_calls              4250 non-null   int64
 14  total_night_charge             4250 non-null   float64
 15  total_intl_minutes             4250 non-null   float64
 16  total_intl_calls               4250 non-null   int64
 17  total_intl_charge              4250 non-null   float64
 18  number_customer_service_calls  4250 non-null   int64
 19  churn                          4250 non-null   object
dtypes: float64(8), int64(7), object(5)
memory usage: 664.2+ KB

In [37]:
data.describe()

,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
count,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000,4250.000000
mean,100.236235,7.631765,180.259600,99.907294,30.644682,200.173906,100.176471,17.015012,200.527882,99.839529,9.023892,10.256071,4.426353,2.769654,1.559059
std,39.698401,13.439882,54.012373,19.850817,9.182096,50.249518,19.908591,4.271212,50.353548,20.093220,2.265922,2.760102,2.463069,0.745204,1.311434
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,73.000000,0.000000,143.325000,87.000000,24.365000,165.925000,87.000000,14.102500,167.225000,86.000000,7.522500,8.500000,3.000000,2.300000,1.000000
50%,100.000000,0.000000,180.450000,100.000000,30.680000,200.700000,100.000000,17.060000,200.450000,100.000000,9.020000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,16.000000,216.200000,113.000000,36.750000,233.775000,114.000000,19.867500,234.700000,113.000000,10.560000,12.000000,6.000000,3.240000,2.000000
max,243.000000,52.000000,351.500000,165.000000,59.760000,359.300000,170.000000,30.540000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [38]:
data.churn=(data.churn=="yes").astype(int)
data.churn.value_counts()

0    3652
1     598
Name: churn, dtype: int64

In [39]:
data.churn.nunique()

2

### setting up validation frame work
This involves splitting the data into train validation dataset

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
data_full_train,data_test=train_test_split(data,test_size=0.2,random_state=1)
# i split the data into two with 80% and 20% as train and test data respectively

In [47]:
data_train,data_val=train_test_split(data_full_train,test_size=0.25,random_state=1)
# i split the data into two with 60% and 20% as train and validation data respectively

In [50]:
len(data_full_train),len(data_test),len(data_val)

(3400, 850, 850)

In [51]:
data_train=data_train.reset_index(drop=True)
data_test=data_test.reset_index(drop=True)
data_val=data_val.reset_index(drop=True)

In [53]:
y_train=data_train.churn.values
y_test=data_test.churn.values
y_val=data_val.churn.values

In [54]:
del data_train["churn"]
del data_test["churn"]
del data_val["churn"]

In [58]:
data_train.head(10).T

,0,1,2,3,4,5,6,7,8,9
state,IA,ME,NE,SD,MD,MD,AL,MA,MS,WI
account_length,197,146,154,97,54,5,26,69,158,122
area_code,area_code_415,area_code_415,area_code_415,area_code_415,area_code_415,area_code_408,area_code_408,area_code_510,area_code_510,area_code_510
international_plan,no,no,no,no,no,no,no,no,no,no
voice_mail_plan,no,no,no,no,no,no,no,no,no,yes
number_vmail_messages,0,0,0,0,0,0,0,0,0,28
total_day_minutes,233.9,174.3,191.4,168.6,273.8,198.7,290.1,195.1,175.9,166.0
total_day_calls,96,113,93,87,113,108,143,91,105,62
total_day_charge,39.76,29.63,32.54,28.66,46.55,33.78,49.32,33.17,29.9,28.22
total_eve_minutes,218.9,200.7,205.4,259.2,119.6,146.7,245.7,261.5,188.3,233.9
total_eve_calls,111,107,119,105,156,86,97,57,88,88
total_eve_charge,18.61,17.06,17.46,22.03,10.17,12.47,20.88,22.23,16.01,19.88
total_night_minutes,182.9,281.2,205.7,279.8,267.6,216.8,147.0,203.8,188.3,170.1
total_night_calls,109,145,121,123,117,95,80,90,98,84
total_night_charge,8.23,12.65,9.26,12.59,12.04,9.76,6.61,9.17,8.47,7.65
total_intl_minutes,9.5,11.6,10.2,7.3,11.7,9.5,7.4,11.4,11.0,7.7
total_intl_calls,3,3,3,4,3,3,4,5,6,3
total_intl_charge,2.57,3.13,2.75,1.97,3.16,2.57,2.0,3.08,2.97,2.08
number_customer_service_calls,0,4,3,1,1,2,2,0,1,2

### Eda

In [61]:
data_full_train=data_full_train.reset_index(drop=True)
data_full_train

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,TX,123,area_code_408,no,yes,41,141.3,127,24.02,152.0,96,12.92,218.8,114,9.85,8.1,3,2.19,3,0
1,WV,154,area_code_408,no,yes,35,64.9,76,11.03,184.1,91,15.65,151.6,75,6.82,14.6,1,3.94,1,0
2,AK,104,area_code_415,no,no,0,174.1,97,29.60,174.6,104,14.84,182.7,158,8.22,9.3,4,2.51,3,0
3,MI,126,area_code_415,no,no,0,193.1,114,32.83,75.5,61,6.42,186.2,73,8.38,11.1,1,3.00,3,0
4,AZ,155,area_code_415,yes,no,0,176.1,88,29.94,244.5,84,20.78,189.9,99,8.55,11.2,1,3.02,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,SD,137,area_code_415,no,no,0,144.5,119,24.57,167.3,89,14.22,175.1,76,7.88,6.1,4,1.65,5,1
3396,RI,138,area_code_510,yes,no,0,286.2,61,48.65,187.2,60,15.91,146.2,114,6.58,11.0,4,2.97,2,1
3397,SD,88,area_code_415,no,no,0,215.6,115,36.65,216.2,85,18.38,171.3,65,7.71,11.8,1,3.19,3,0
3398,MN,130,area_code_415,no,no,0,204.5,88,34.77,178.4,85,15.16,229.6,78,10.33,12.6,8,3.40,0,0
3399,SD,145,area_code_408,no,yes,24,147.5,90,25.08,175.7,108,14.93,252.1,102,11.34,15.6,3,4.21,2,0

In [65]:
data_full_train.churn.value_counts(normalize=True)

0    0.859118
1    0.140882
Name: churn, dtype: float64

### from here we can see that 14% of the customers churned

In [70]:
global_churn=data_full_train.churn.mean()
global_churn
# global churn represent the numbers of customers who churned

0.14088235294117646

In [104]:
data_types=data_full_train.dtypes
print(data_types)

state                             object
account_length                     int64
area_code                         object
international_plan                object
voice_mail_plan                   object
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                              int64
dtype: object

In [69]:
data_full_train.columns

Index(['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn'],
      dtype='object')

In [128]:
numeric = ['account_length',
 'number_vmail_messages',
 'total_day_minutes',
 'total_day_calls',
 'total_day_charge',
 'total_eve_minutes',
 'total_eve_calls',
 'total_eve_charge',
 'total_night_minutes',
 'total_night_calls',
 'total_night_charge',
 'total_intl_minutes',
 'total_intl_calls',
 'total_intl_charge',
 'number_customer_service_calls']
numeric

['account_length',
 'number_vmail_messages',
 'total_day_minutes',
 'total_day_calls',
 'total_day_charge',
 'total_eve_minutes',
 'total_eve_calls',
 'total_eve_charge',
 'total_night_minutes',
 'total_night_calls',
 'total_night_charge',
 'total_intl_minutes',
 'total_intl_calls',
 'total_intl_charge',
 'number_customer_service_calls']

In [129]:
categorical=data_full_train.select_dtypes(include=['object']).columns.tolist()
categorical

['state', 'area_code', 'international_plan', 'voice_mail_plan']

In [130]:
data_full_train[categorical].nunique()

state                 51
area_code              3
international_plan     2
voice_mail_plan        2
dtype: int64

## feature selection/ importance using Risk ratio and difference

In [131]:
for c in categorical:
    print(c)
    data_group=data_full_train.groupby(c).churn.agg(["mean","count"])
    data_group['diff']=data_group["mean"] - global_churn
    data_group["risk"]=data_group["mean"]/global_churn
    display(data_group)

state

           mean  count      diff      risk
state
AK     0.074074     54 -0.066808  0.525787
AL     0.123596     89 -0.017287  0.877296
AR     0.160714     56  0.019832  1.140769
AZ     0.093750     64 -0.047132  0.665449
CA     0.212121     33  0.071239  1.505662
CO     0.115942     69 -0.024940  0.822971
CT     0.180556     72  0.039673  1.281605
DC     0.109091     55 -0.031791  0.774340
DE     0.181818     66  0.040936  1.290567
FL     0.125000     64 -0.015882  0.887265
GA     0.103448     58 -0.037434  0.734288
HI     0.032258     62 -0.108624  0.228972
IA     0.083333     48 -0.057549  0.591510
ID     0.111111     81 -0.029771  0.788680
IL     0.078125     64 -0.062757  0.554541
IN     0.176471     68  0.035588  1.252610
KS     0.147059     68  0.006176  1.043841
KY     0.117647     68 -0.023235  0.835073
LA     0.100000     50 -0.040882  0.709812
MA     0.159420     69  0.018538  1.131585
MD     0.250000     72  0.109118  1.774530
ME     0.177215     79  0.036333  1.257895
MI     0.183099     71  0.042216  1.299656
MN     0.152941     85  0.012059  1.085595
MO     0.158730     63  0.017848  1.126686
MS     0.209677     62  0.068795  1.488316
MT     0.217391     69  0.076509  1.543070
NC     0.088235     68 -0.052647  0.626305
ND     0.084746     59 -0.056137  0.601536
NE     0.055556     54 -0.085327  0.394340
NH     0.160714     56  0.019832  1.140769
NJ     0.273973     73  0.133090  1.944691
NM     0.136364     66 -0.004519  0.967926
NV     0.193548     62  0.052666  1.373830
NY     0.179487     78  0.038605  1.274022
OH     0.116883     77 -0.023999  0.829651
OK     0.213115     61  0.072232  1.512714
OR     0.133333     75 -0.007549  0.946416
PA     0.132075     53 -0.008807  0.937488
RI     0.068493     73 -0.072389  0.486173
SC     0.160714     56  0.019832  1.140769
SD     0.140351     57 -0.000531  0.996228
TN     0.181818     55  0.040936  1.290567
TX     0.223684     76  0.082802  1.587738
UT     0.157895     76  0.017012  1.120756
VA     0.058824     85 -0.082059  0.417537
VT     0.142857     63  0.001975  1.014017
WA     0.233333     60  0.092451  1.656228
WI     0.064103     78 -0.076780  0.455008
WV     0.109091    110 -0.031791  0.774340
WY     0.057143     70 -0.083739  0.405607

area_code

                   mean  count      diff      risk
area_code
area_code_408  0.140371    862 -0.000511  0.996372
area_code_415  0.134002   1694 -0.006880  0.951165
area_code_510  0.155213    844  0.014331  1.101723

international_plan

                        mean  count      diff      risk
international_plan
no                  0.111866   3093 -0.029017  0.794035
yes                 0.433225    307  0.292342  3.075082

voice_mail_plan

                     mean  count      diff      risk
voice_mail_plan
no               0.165605   2512  0.024723  1.175485
yes              0.070946    888 -0.069936  0.503583

#### from here we can see that people with international plan are more likely to churn and people with voice mail plan are less likely to churn and also, state and area code features has low risk ratio and diffrerence score respectively, so its safe to drop these features

## Feature importance mutual information

In [132]:
from sklearn.metrics import mutual_info_score

In [133]:
def mutual_info(series):
    return mutual_info_score(series,data_full_train.churn)

In [134]:
m_info=data_full_train[categorical].apply(mutual_info)
m_info.sort_values(ascending=False)

international_plan    0.026023
state                 0.012804
voice_mail_plan       0.008060
area_code             0.000304
dtype: float64

##### The categorical columns has low mutual scores it is safe to drop some of  them

In [135]:
m_info=data_full_train[numeric].apply(mutual_info)
m_info.sort_values(ascending=False)

/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/metrics/cluster/_supervised.py:65: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)

total_day_minutes                0.273328
total_day_charge                 0.273328
total_eve_minutes                0.227023
total_night_minutes              0.221156
total_eve_charge                 0.206633
total_night_charge               0.141294
number_customer_service_calls    0.035077
account_length                   0.033756
total_intl_minutes               0.027246
total_intl_charge                0.027246
total_day_calls                  0.019102
total_eve_calls                  0.016754
total_night_calls                0.016579
number_vmail_messages            0.015469
total_intl_calls                 0.005998
dtype: float64

### feature importance correlation

In [136]:
data_full_train[numeric].corrwith(data_full_train.churn)

account_length                   0.015714
number_vmail_messages           -0.102305
total_day_minutes                0.214927
total_day_calls                  0.004966
total_day_charge                 0.214916
total_eve_minutes                0.084465
total_eve_calls                  0.009780
total_eve_charge                 0.084462
total_night_minutes              0.057289
total_night_calls               -0.007333
total_night_charge               0.057270
total_intl_minutes               0.057280
total_intl_calls                -0.048358
total_intl_charge                0.057245
number_customer_service_calls    0.219389
dtype: float64

### one hot encoding with dict vectoriser

In [127]:
from sklearn.feature_extraction import DictVectorizer

In [137]:
train_dicts=data_train[categorical+numeric].to_dict(orient='record')
train_dicts[0]

/var/folders/zp/12tgv94s36x_34hdc9gjmywh0000gn/T/ipykernel_18575/4236755364.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  train_dicts=data_train[categorical+numeric].to_dict(orient='record')

{'state': 'IA',
 'area_code': 'area_code_415',
 'international_plan': 'no',
 'voice_mail_plan': 'no',
 'account_length': 197,
 'number_vmail_messages': 0,
 'total_day_minutes': 233.9,
 'total_day_calls': 96,
 'total_day_charge': 39.76,
 'total_eve_minutes': 218.9,
 'total_eve_calls': 111,
 'total_eve_charge': 18.61,
 'total_night_minutes': 182.9,
 'total_night_calls': 109,
 'total_night_charge': 8.23,
 'total_intl_minutes': 9.5,
 'total_intl_calls': 3,
 'total_intl_charge': 2.57,
 'number_customer_service_calls': 0}

In [143]:
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)
X_train=dv.transform(train_dicts)
dv.get_feature_names()

['account_length',
 'area_code=area_code_408',
 'area_code=area_code_415',
 'area_code=area_code_510',
 'international_plan=no',
 'international_plan=yes',
 'number_customer_service_calls',
 'number_vmail_messages',
 'state=AK',
 'state=AL',
 'state=AR',
 'state=AZ',
 'state=CA',
 'state=CO',
 'state=CT',
 'state=DC',
 'state=DE',
 'state=FL',
 'state=GA',
 'state=HI',
 'state=IA',
 'state=ID',
 'state=IL',
 'state=IN',
 'state=KS',
 'state=KY',
 'state=LA',
 'state=MA',
 'state=MD',
 'state=ME',
 'state=MI',
 'state=MN',
 'state=MO',
 'state=MS',
 'state=MT',
 'state=NC',
 'state=ND',
 'state=NE',
 'state=NH',
 'state=NJ',
 'state=NM',
 'state=NV',
 'state=NY',
 'state=OH',
 'state=OK',
 'state=OR',
 'state=PA',
 'state=RI',
 'state=SC',
 'state=SD',
 'state=TN',
 'state=TX',
 'state=UT',
 'state=VA',
 'state=VT',
 'state=WA',
 'state=WI',
 'state=WV',
 'state=WY',
 'total_day_calls',
 'total_day_charge',
 'total_day_minutes',
 'total_eve_calls',
 'total_eve_charge',
 'total_eve_minutes',
 'total_intl_calls',
 'total_intl_charge',
 'total_intl_minutes',
 'total_night_calls',
 'total_night_charge',
 'total_night_minutes',
 'voice_mail_plan=no',
 'voice_mail_plan=yes']

In [144]:
X_train.shape

(2550, 73)

In [146]:
val_dict=data_val[categorical+numeric].to_dict(orient='record')
val_dict[0]

/var/folders/zp/12tgv94s36x_34hdc9gjmywh0000gn/T/ipykernel_18575/3545376402.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  val_dict=data_val[categorical+numeric].to_dict(orient='record')

{'state': 'NM',
 'area_code': 'area_code_415',
 'international_plan': 'no',
 'voice_mail_plan': 'no',
 'account_length': 143,
 'number_vmail_messages': 0,
 'total_day_minutes': 271.7,
 'total_day_calls': 67,
 'total_day_charge': 46.19,
 'total_eve_minutes': 189.1,
 'total_eve_calls': 155,
 'total_eve_charge': 16.07,
 'total_night_minutes': 101.1,
 'total_night_calls': 55,
 'total_night_charge': 4.55,
 'total_intl_minutes': 17.2,
 'total_intl_calls': 5,
 'total_intl_charge': 4.64,
 'number_customer_service_calls': 1}

In [149]:
X_val=dv.transform(val_dict)
X_val.shape

(850, 73)

### Logistic regression model

In [150]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [152]:
pred_1 = model.predict_proba(X_val)[:,1]
pred_1

array([0.27653144, 0.25631419, 0.13457661, 0.25620832, 0.05583093,
       0.14441553, 0.02501735, 0.10801965, 0.02954295, 0.29720701,
       0.04615459, 0.06693991, 0.14031739, 0.25857512, 0.82111823,
       0.5277295 , 0.11153128, 0.06470895, 0.29006356, 0.07816127,
       0.05013344, 0.02967291, 0.01005173, 0.13482747, 0.0349687 ,
       0.12801941, 0.09272616, 0.08890873, 0.12867989, 0.07213498,
       0.13933091, 0.06323428, 0.06166754, 0.23200334, 0.16615692,
       0.32100283, 0.03375835, 0.11759398, 0.06219014, 0.02839603,
       0.04452726, 0.39668336, 0.15514832, 0.2079287 , 0.07501556,
       0.14672295, 0.68854792, 0.06560161, 0.1664609 , 0.09014495,
       0.15360348, 0.03392579, 0.02467357, 0.1800987 , 0.09233392,
       0.16458403, 0.1751186 , 0.11066619, 0.05931134, 0.15316172,
       0.24692637, 0.06330296, 0.15175022, 0.06868889, 0.07511045,
       0.04443172, 0.1012332 , 0.24279165, 0.040679  , 0.65375328,
       0.07316932, 0.29706341, 0.04340397, 0.03580977, 0.18778578,
       0.13179623, 0.16285322, 0.06118976, 0.28356483, 0.09917378,
       0.10946529, 0.11885201, 0.18163905, 0.29849833, 0.06701236,
       0.2347777 , 0.06032597, 0.2551049 , 0.15988517, 0.06592137,
       0.10468516, 0.03401371, 0.05969693, 0.18164176, 0.20958077,
       0.17135912, 0.09959112, 0.15342883, 0.09039193, 0.55745779,
       0.06507327, 0.04632609, 0.01130234, 0.28718706, 0.45462808,
       0.31437043, 0.08131562, 0.09607135, 0.06986557, 0.15699152,
       0.16784335, 0.32293237, 0.02535823, 0.06143976, 0.07757546,
       0.62346875, 0.37010789, 0.06479388, 0.206486  , 0.37899547,
       0.13630036, 0.11794708, 0.11072824, 0.1108127 , 0.18551285,
       0.11312249, 0.07077628, 0.03235395, 0.02805869, 0.00377736,
       0.06565703, 0.04592032, 0.01709599, 0.06812367, 0.08095475,
       0.30471282, 0.04711863, 0.06430361, 0.05450186, 0.03818743,
       0.1453326 , 0.06361404, 0.10491832, 0.0194598 , 0.13330831,
       0.1027154 , 0.37192327, 0.02270299, 0.13837351, 0.1125621 ,
       0.03614521, 0.07524416, 0.10443734, 0.19174087, 0.05002204,
       0.02196211, 0.22553412, 0.05955594, 0.39661177, 0.37339683,
       0.14111703, 0.20894759, 0.13708374, 0.19121904, 0.01523939,
       0.53564514, 0.01518317, 0.49813206, 0.04279995, 0.03241053,
       0.20381934, 0.29256736, 0.09589997, 0.03104908, 0.20184911,
       0.22390261, 0.02283141, 0.09342079, 0.06293211, 0.335435  ,
       0.1076096 , 0.06620496, 0.1157821 , 0.33274203, 0.07376428,
       0.08036141, 0.16087494, 0.06763957, 0.05884436, 0.3460458 ,
       0.11380568, 0.10536536, 0.15702803, 0.27310067, 0.05540767,
       0.20924465, 0.08794721, 0.1176501 , 0.30483415, 0.05981216,
       0.04692721, 0.21876505, 0.34640506, 0.18638404, 0.07362161,
       0.08594013, 0.03127966, 0.10608047, 0.07420848, 0.15841313,
       0.07555921, 0.03201978, 0.05940033, 0.2150931 , 0.07278149,
       0.14999709, 0.06508498, 0.04409146, 0.00722268, 0.01577629,
       0.14218655, 0.15438857, 0.01434531, 0.03607141, 0.10017945,
       0.10681782, 0.06867437, 0.0130647 , 0.4810616 , 0.19621978,
       0.08763927, 0.36852541, 0.03521046, 0.07357193, 0.21344007,
       0.10301928, 0.05343371, 0.0327419 , 0.4099322 , 0.04626139,
       0.18731929, 0.40347166, 0.01884862, 0.1165573 , 0.0971688 ,
       0.25695262, 0.17868242, 0.23821054, 0.30147448, 0.04078842,
       0.03875189, 0.09118051, 0.11527196, 0.04028465, 0.05256475,
       0.04469046, 0.02481692, 0.094816  , 0.13163271, 0.07135931,
       0.11213904, 0.01344211, 0.19127426, 0.03360912, 0.09666647,
       0.14262881, 0.1283401 , 0.12373221, 0.10944357, 0.01143231,
       0.20911764, 0.08262703, 0.20628889, 0.14120924, 0.10547116,
       0.06790847, 0.06976481, 0.05005419, 0.16780222, 0.04335673,
       0.09728267, 0.16856801, 0.25074305, 0.24307843, 0.23981651,
       0.17153745, 0.15719279, 0.07276333, 0.1311462 , 0.13286315,
       0.11341748, 0.09055246, 0.02599642, 0.12350373, 0.09815685,
       0.31085871, 0.10357429, 0.04053369, 0.16713233, 0.19285228,
       0.25430328, 0.13140663, 0.20232933, 0.07827987, 0.15662995,
       0.060338  , 0.03215036, 0.02506435, 0.08891186, 0.25657351,
       0.08019055, 0.04699596, 0.02556458, 0.02333346, 0.06838649,
       0.13436162, 0.10816086, 0.17632636, 0.27927518, 0.15779893,
       0.196395  , 0.59374904, 0.20974602, 0.07957835, 0.18099994,
       0.15000192, 0.01812186, 0.1440796 , 0.10766538, 0.17292259,
       0.20292356, 0.09737263, 0.12168778, 0.19721968, 0.21277781,
       0.07933518, 0.07454026, 0.20245892, 0.10897587, 0.12770842,
       0.34264103, 0.0319503 , 0.21183762, 0.0760437 , 0.19192459,
       0.25295975, 0.37930885, 0.12155029, 0.13937327, 0.04253765,
       0.21486295, 0.30433337, 0.12750292, 0.01348833, 0.13302882,
       0.11004114, 0.11079909, 0.19832629, 0.35113206, 0.09221783,
       0.15918086, 0.11796383, 0.19165827, 0.20900099, 0.17597694,
       0.17620206, 0.00195284, 0.06661024, 0.11406341, 0.03036224,
       0.12701956, 0.05489203, 0.1123605 , 0.21420355, 0.19448994,
       0.07530697, 0.17057746, 0.33431141, 0.06027018, 0.04471583,
       0.1202122 , 0.08652519, 0.12213471, 0.04166541, 0.03279982,
       0.02995944, 0.00640441, 0.10162436, 0.00881672, 0.26510309,
       0.16142757, 0.05560916, 0.21764244, 0.02697145, 0.22582701,
       0.1333486 , 0.0596754 , 0.08865599, 0.1380337 , 0.11144631,
       0.12141251, 0.05936919, 0.24319924, 0.16463594, 0.4219273 ,
       0.48539966, 0.09046227, 0.24460475, 0.08372628, 0.11082214,
       0.46788614, 0.08064292, 0.09900311, 0.60588563, 0.08045341,
       0.10700579, 0.06308288, 0.04956525, 0.19551425, 0.06557351,
       0.12842062, 0.43671003, 0.12974476, 0.03919686, 0.10353474,
       0.22587697, 0.57917964, 0.1216056 , 0.03523314, 0.0460506 ,
       0.29951665, 0.08234638, 0.02130145, 0.07029757, 0.06193946,
       0.20305123, 0.01272206, 0.0168323 , 0.0728585 , 0.1571974 ,
       0.02103322, 0.08166237, 0.1148522 , 0.16041635, 0.03827808,
       0.08278148, 0.14217353, 0.11086235, 0.34624777, 0.11494631,
       0.11900904, 0.03549978, 0.03636086, 0.0400589 , 0.08438571,
       0.49120231, 0.38845075, 0.15229376, 0.05990938, 0.07166505,
       0.1015153 , 0.07014537, 0.09902821, 0.06678837, 0.2201981 ,
       0.02637367, 0.1685209 , 0.09879029, 0.03450992, 0.05850192,
       0.05888465, 0.03607001, 0.27047829, 0.16897427, 0.12811433,
       0.31927363, 0.24684382, 0.1264359 , 0.03858182, 0.07475915,
       0.26212098, 0.3078537 , 0.07512877, 0.0293767 , 0.06804697,
       0.05131235, 0.03143776, 0.19326515, 0.13921251, 0.13471979,
       0.12279537, 0.06290459, 0.09689459, 0.06189281, 0.12512726,
       0.08004126, 0.2633944 , 0.11346832, 0.06648881, 0.09209747,
       0.19558922, 0.15198367, 0.23432311, 0.0350488 , 0.14433663,
       0.38315201, 0.41575429, 0.10964552, 0.11729708, 0.03417163,
       0.03491292, 0.14099921, 0.06282411, 0.20635594, 0.04313108,
       0.01759896, 0.06977982, 0.03890945, 0.0644609 , 0.15815956,
       0.2235148 , 0.03220595, 0.01463178, 0.14296847, 0.09919172,
       0.1589136 , 0.09939778, 0.13771314, 0.12881756, 0.21166618,
       0.28558337, 0.03644583, 0.07085985, 0.28453067, 0.11391248,
       0.05193706, 0.07707925, 0.04953977, 0.18666546, 0.06648755,
       0.03197764, 0.1230342 , 0.18097393, 0.12763881, 0.03997957,
       0.12159399, 0.014099  , 0.19906585, 0.12035175, 0.06892229,
       0.21553358, 0.09931523, 0.07090265, 0.07416388, 0.28793421,
       0.0948911 , 0.09807953, 0.15872286, 0.01806997, 0.08749858,
       0.02641071, 0.38442257, 0.23316848, 0.05071662, 0.08839294,
       0.07758792, 0.01495368, 0.4700721 , 0.07689277, 0.08123081,
       0.10094535, 0.05589736, 0.09338583, 0.62716076, 0.02503275,
       0.15883034, 0.4252909 , 0.11607221, 0.14641587, 0.07789203,
       0.10382647, 0.0157662 , 0.03726878, 0.07375479, 0.20399956,
       0.109171  , 0.03446008, 0.38436635, 0.04908387, 0.3740368 ,
       0.15165301, 0.20815815, 0.29177591, 0.01166985, 0.0794607 ,
       0.11276706, 0.07433162, 0.126166  , 0.1038927 , 0.23301901,
       0.05894305, 0.15180336, 0.3915658 , 0.05737373, 0.05598128,
       0.14281155, 0.44224546, 0.07925671, 0.27698141, 0.14316196,
       0.02354913, 0.10492315, 0.09402243, 0.04185035, 0.07737015,
       0.04940734, 0.45974345, 0.02684503, 0.02610422, 0.12652929,
       0.07777796, 0.10481639, 0.33740064, 0.10672726, 0.2089521 ,
       0.10787123, 0.09628973, 0.29427745, 0.06637299, 0.15973978,
       0.08785453, 0.16916584, 0.20486608, 0.53108458, 0.2923986 ,
       0.02844038, 0.05397256, 0.58574923, 0.12938528, 0.19535108,
       0.14221923, 0.2813152 , 0.11700745, 0.19993898, 0.05579634,
       0.0854005 , 0.09087289, 0.0974697 , 0.08858917, 0.18052902,
       0.11995683, 0.11650642, 0.0884135 , 0.12114789, 0.02362065,
       0.01149843, 0.07917621, 0.03113107, 0.03864168, 0.04618787,
       0.09800645, 0.03817596, 0.22684843, 0.08008116, 0.0610428 ,
       0.27595008, 0.04541705, 0.23876691, 0.08029449, 0.1008144 ,
       0.09690765, 0.05865015, 0.03105402, 0.05199939, 0.03754271,
       0.2642433 , 0.03911149, 0.26431708, 0.0216139 , 0.02838279,
       0.10690411, 0.03578299, 0.1385382 , 0.22400708, 0.04695295,
       0.1701437 , 0.06327652, 0.14050113, 0.49117251, 0.27197668,
       0.39797477, 0.05940656, 0.15234101, 0.16084227, 0.15002361,
       0.05723469, 0.05762158, 0.05938294, 0.0726405 , 0.09039038,
       0.2392664 , 0.10295814, 0.14202282, 0.35063676, 0.08723651,
       0.57697812, 0.05441738, 0.09567002, 0.43174173, 0.13318831,
       0.18515193, 0.01353156, 0.05837277, 0.12859876, 0.04831169,
       0.03001466, 0.26715466, 0.13155712, 0.38137546, 0.15683953,
       0.25628265, 0.10511352, 0.08578643, 0.66841753, 0.1639086 ,
       0.1354976 , 0.3327078 , 0.08393612, 0.13396543, 0.20708314,
       0.02898369, 0.07247556, 0.01101354, 0.1955272 , 0.29893586,
       0.2691293 , 0.31721637, 0.24425736, 0.41179264, 0.03695759,
       0.44214508, 0.13384701, 0.0573039 , 0.14047042, 0.02707137,
       0.1742015 , 0.01964364, 0.13209677, 0.03645639, 0.03436938,
       0.36186559, 0.11158094, 0.47178706, 0.06310471, 0.01372722,
       0.05720169, 0.08170405, 0.12778584, 0.11062725, 0.06866106,
       0.13775348, 0.14038102, 0.21305894, 0.33716946, 0.03446062,
       0.01829701, 0.06942115, 0.07364292, 0.05532088, 0.17936757,
       0.26264231, 0.07075937, 0.03368742, 0.12689864, 0.10413504,
       0.03050924, 0.16078775, 0.0817643 , 0.08085761, 0.27799008,
       0.04662804, 0.10083864, 0.55426425, 0.12883214, 0.10843247,
       0.26611441, 0.06797314, 0.05198842, 0.24601409, 0.07357341,
       0.16631448, 0.19817821, 0.12004246, 0.19621418, 0.13888941,
       0.20971995, 0.04863754, 0.03837823, 0.06800462, 0.14298972,
       0.1332022 , 0.11629107, 0.11931548, 0.32294488, 0.08860742,
       0.33925746, 0.30962473, 0.00763456, 0.20224109, 0.1963126 ,
       0.0530237 , 0.0117172 , 0.12087514, 0.06272665, 0.0538875 ,
       0.03805666, 0.08896024, 0.28657257, 0.05491296, 0.1246568 ,
       0.25162248, 0.0761863 , 0.05691048, 0.09251307, 0.01843801,
       0.20119467, 0.19793185, 0.14750241, 0.07203172, 0.23375147,
       0.11156809, 0.06814287, 0.43583146, 0.15520628, 0.29489402,
       0.00854445, 0.23558326, 0.08163206, 0.19072359, 0.0788898 ,
       0.09297984, 0.15753889, 0.09045885, 0.22693803, 0.458651  ,
       0.1093339 , 0.04245837, 0.04754863, 0.0550418 , 0.05839484])

In [153]:
churn_decision=(pred_1 >= 0.5)

### model interpretation

In [157]:
model.coef_[0].round(3) ### this is the weight of each features

array([-0.002, -0.026, -0.046,  0.009, -0.315,  0.252,  0.44 , -0.031,
       -0.008, -0.01 ,  0.002, -0.011,  0.017, -0.011,  0.009, -0.001,
       -0.003, -0.009, -0.008, -0.017, -0.009, -0.004, -0.011,  0.005,
       -0.   , -0.007, -0.001, -0.004,  0.01 ,  0.006,  0.011,  0.009,
       -0.003,  0.011,  0.02 , -0.011, -0.009, -0.013,  0.005,  0.031,
       -0.007,  0.002,  0.008, -0.005,  0.001, -0.003, -0.002, -0.018,
        0.006, -0.007,  0.008,  0.019, -0.005, -0.015, -0.007,  0.019,
       -0.015, -0.009, -0.019, -0.012,  0.001,  0.009, -0.009,  0.   ,
        0.001, -0.107,  0.001,  0.003, -0.014, -0.   ,  0.   , -0.03 ,
       -0.033])

In [159]:
dv.get_feature_names()

/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['account_length',
 'area_code=area_code_408',
 'area_code=area_code_415',
 'area_code=area_code_510',
 'international_plan=no',
 'international_plan=yes',
 'number_customer_service_calls',
 'number_vmail_messages',
 'state=AK',
 'state=AL',
 'state=AR',
 'state=AZ',
 'state=CA',
 'state=CO',
 'state=CT',
 'state=DC',
 'state=DE',
 'state=FL',
 'state=GA',
 'state=HI',
 'state=IA',
 'state=ID',
 'state=IL',
 'state=IN',
 'state=KS',
 'state=KY',
 'state=LA',
 'state=MA',
 'state=MD',
 'state=ME',
 'state=MI',
 'state=MN',
 'state=MO',
 'state=MS',
 'state=MT',
 'state=NC',
 'state=ND',
 'state=NE',
 'state=NH',
 'state=NJ',
 'state=NM',
 'state=NV',
 'state=NY',
 'state=OH',
 'state=OK',
 'state=OR',
 'state=PA',
 'state=RI',
 'state=SC',
 'state=SD',
 'state=TN',
 'state=TX',
 'state=UT',
 'state=VA',
 'state=VT',
 'state=WA',
 'state=WI',
 'state=WV',
 'state=WY',
 'total_day_calls',
 'total_day_charge',
 'total_day_minutes',
 'total_eve_calls',
 'total_eve_charge',
 'total_eve_minutes',
 'total_intl_calls',
 'total_intl_charge',
 'total_intl_minutes',
 'total_night_calls',
 'total_night_charge',
 'total_night_minutes',
 'voice_mail_plan=no',
 'voice_mail_plan=yes']

In [160]:
dict(zip(model.coef_[0].round(3),dv.get_feature_names()))

/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

{-0.002: 'state=PA',
 -0.026: 'area_code=area_code_408',
 -0.046: 'area_code=area_code_415',
 0.009: 'total_day_minutes',
 -0.315: 'international_plan=no',
 0.252: 'international_plan=yes',
 0.44: 'number_customer_service_calls',
 -0.031: 'number_vmail_messages',
 -0.008: 'state=GA',
 -0.01: 'state=AL',
 0.002: 'state=NV',
 -0.011: 'state=NC',
 0.017: 'state=CA',
 -0.001: 'state=LA',
 -0.003: 'state=OR',
 -0.009: 'total_eve_calls',
 -0.017: 'state=HI',
 -0.004: 'state=MA',
 0.005: 'state=NH',
 -0.0: 'total_night_minutes',
 -0.007: 'state=VT',
 0.01: 'state=MD',
 0.006: 'state=SC',
 0.011: 'state=MS',
 0.02: 'state=MT',
 -0.013: 'state=NE',
 0.031: 'state=NJ',
 0.008: 'state=TN',
 -0.005: 'state=UT',
 0.001: 'total_intl_charge',
 -0.018: 'state=RI',
 0.019: 'state=WA',
 -0.015: 'state=WI',
 -0.019: 'state=WY',
 -0.012: 'total_day_calls',
 -0.107: 'total_intl_calls',
 0.003: 'total_intl_minutes',
 -0.014: 'total_night_calls',
 -0.03: 'voice_mail_plan=no',
 -0.033: 'voice_mail_plan=yes'}

### using the model (logistic_regression)

#### after training the model with 60% of the dataset, we then train with 80% of the data set and test with the 20% test dataset

In [161]:
dicts_full_train=data_full_train[categorical+numeric].to_dict(orient="record")

/var/folders/zp/12tgv94s36x_34hdc9gjmywh0000gn/T/ipykernel_18575/4128062341.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  dicts_full_train=data_full_train[categorical+numeric].to_dict(orient="record")

In [162]:
dv_full_train=dv.fit(dicts_full_train)

In [163]:
X_full_train=dv.transform(dicts_full_train)

In [164]:
Y_full_train=data_full_train.churn.values

In [165]:
model=LogisticRegression()
model.fit(X_full_train,Y_full_train)

/Users/victoroshimua/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [166]:
dicts_test=data_test[categorical+numeric].to_dict(orient="record")
X_test=dv.transform(dicts_test)

/var/folders/zp/12tgv94s36x_34hdc9gjmywh0000gn/T/ipykernel_18575/3880004527.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  dicts_test=data_test[categorical+numeric].to_dict(orient="record")

In [167]:
y_pred=model.predict_proba(X_test)[:,1]
churn_decision_= (y_pred>=0.5)

In [168]:
(churn_decision_==y_test).mean()

0.8635294117647059

In [169]:
from sklearn.metrics import accuracy_score

In [172]:
accuracy_score(y_test,churn_decision_,normalize=True)

0.8635294117647059

## Testing the model with new test dataset

In [174]:
test=pd.read_csv("test.csv")

In [176]:
test.head().T

,0,1,2,3,4
id,1,2,3,4,5
state,KS,AL,IA,VT,NE
account_length,128,118,62,93,174
area_code,area_code_415,area_code_510,area_code_415,area_code_510,area_code_415
international_plan,no,yes,no,no,no
voice_mail_plan,yes,no,no,no,no
number_vmail_messages,25,0,0,0,0
total_day_minutes,265.1,223.4,120.7,190.7,124.3
total_day_calls,110,98,70,114,76
total_day_charge,45.07,37.98,20.52,32.42,21.13
total_eve_minutes,197.4,220.6,307.2,218.2,277.1
total_eve_calls,99,101,76,111,112
total_eve_charge,16.78,18.75,26.11,18.55,23.55
total_night_minutes,244.7,203.9,203.0,129.6,250.7
total_night_calls,91,118,99,121,115
total_night_charge,11.01,9.18,9.14,5.83,11.28
total_intl_minutes,10.0,6.3,13.1,8.1,15.5
total_intl_calls,3,6,6,3,5
total_intl_charge,2.7,1.7,3.54,2.19,4.19
number_customer_service_calls,1,0,4,3,3

In [177]:
del test["id"]

In [178]:
test.head()

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
0,KS,128,area_code_415,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1
1,AL,118,area_code_510,yes,no,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0
2,IA,62,area_code_415,no,no,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4
3,VT,93,area_code_510,no,no,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3
4,NE,174,area_code_415,no,no,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3

In [188]:
test_dict_= test[numeric+categorical].to_dict(orient="record")
len(test_dict_)

/var/folders/zp/12tgv94s36x_34hdc9gjmywh0000gn/T/ipykernel_18575/3133979099.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  test_dict_= test[numeric+categorical].to_dict(orient="record")

750

In [180]:
dv.fit(test_dict_)
test_data_=dv.transform(test_dict_)

In [182]:
pred_2=model.predict_proba(test_data_)[:,1]

In [183]:
churn_decision_2=(pred_2>=0.5)